Repository kyma-project/template-operator, pull requests merged in 2023-09, with the labels that each got.

#83 Resolve todo and remove helm related code
  .golangci.yaml
  PROJECT
  README.md
  api/v1alpha1/samplehelm_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_samplehelms.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_samplehelms.yaml
  config/crd/patches/webhook_in_samplehelms.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/rbac/samplehelm_editor_role.yaml
  config/rbac/samplehelm_viewer_role.yaml
  controllers/common_utils.go
  controllers/rest_getter_proxy.go
  controllers/sample_controller_rendered_resources.go
  controllers/sample_local_helm_controller.go
  controllers/sample_local_helm_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  module-data/README.md
  template.yaml
Labels: lgtm, size/XXL

#86 add module config
  Makefile
  config/crd/bases/operator.kyma-project.io_samples.yaml
  config/rbac/role.yaml
  mod/component-descriptor.yaml
  module-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/M

#87 add version prefix
  module-config.yaml
Labels: size/XS, lgtm

#88 Fix operator roles
  config/rbac/role.yaml
  controllers/sample_controller_rendered_resources.go
Labels: lgtm, size/S

#77 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: lgtm, size/L

#91 Add new fields to the sec scanners config file
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#93 chore(infra): Adjust GitHub Action linters
  .github/dependabot.yml
  .github/workflows/lint-conventional-prs.yml
  .github/workflows/lint-markdown-links.yml
  .mlc.config.json
  CODE_OF_CONDUCT.md
  README.md
Labels: lgtm, area/ci, size/M
