Repository kyma-project/template-operator, pull requests merged in 2023-12, with the labels that each got.

#132 chore: Set new versions for release
  .version
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#133 chore(report): Adds a sprint commits report
  .github/workflows/report-sprint-commits.yml
Labels: lgtm, area/ci, size/S, cla: yes

#137 chore(report): Adjusts the "Sprint Commits Test Suites" report to report E2E and Integration tests separately
  .github/workflows/report-sprint-commits.yml
Labels: size/XS, lgtm, area/ci, cla: yes
