Repository kyma-project/template-operator, pull requests merged in 2023-11, with the labels that each got.

#108 docs(README.md): Update Module Build Documentation
  README.md
  hack/local-template.sh
Labels: lgtm, size/L

#115 chore: Add TWs to codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#119 chore(github): Adjust PR title linting config
  .github/workflows/lint-conventional-prs.yml
Labels: size/XS, lgtm, area/ci

#117 feat: Add release workflow dispatch
  .github/workflows/create-release.yml
  .version
  Dockerfile
  README.md
  config/samples/default-sample-cr.yaml
  main.go
  module-config.yaml
  scripts/local/patch_template_file.sh
  scripts/release/create_changelog.sh
  scripts/release/draft_release.sh
  scripts/release/publish_release.sh
  scripts/release/upload_assets.sh
  scripts/release/validate_pipeline_status.sh
  scripts/release/validate_versions.sh
  sec-scanners-config.yaml
Labels: lgtm, area/ci, size/L

#124 fix: Set current version for template-operator
  module-config.yaml
Labels: size/XS, lgtm

#125 fix: Reintroduce rc-tag in sec-scanners-config
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#127 fix: Reintroduce dev-branch to sec scanner cfg
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#129 feat: Add make targets for asset upload
  Makefile
  scripts/local/get_kyma_file_name.sh
  scripts/release/upload_assets.sh
Labels: lgtm, size/M, cla: yes
