Repository kyma-project/template-operator, pull requests merged in 2023-10, with the labels that each got.

#101 chore: Update channel to regular
  module-config.yaml
Labels: size/XS, lgtm

#105 chore: Bump dependencies
  go.mod
  go.sum
  main.go
Labels: size/XL, lgtm

#110 feat: make api as module
  Dockerfile
  api/go.mod
  api/go.sum
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/sample_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/sample_controller_rendered_resources.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: lgtm, size/L
