Repository kyma-project/template-operator, pull requests merged in 2024-07, with the labels that each got.

#219 fix: Change third party crd folder
  Makefile
  crd/operator.kyma-project.io_thirdparties.yaml
Labels: size/XS, lgtm, cla: yes

#225 chore: Bump k8s deps
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#226 chore: Remove unneeded default directory
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, size/M, cla: yes

#227 chore: Add deprecation note for customStateCheck
  README.md
Labels: size/XS, lgtm, cla: yes
