Repository kyma-project/template-operator, pull requests merged in 2024-09, with the labels that each got.

#245 fix: Upload assets from github action
  .github/workflows/create-release.yml
  scripts/release/upload_assets.sh
Labels: lgtm, area/ci, size/S, cla: yes

#243 feat: Add GitHub Action for template-operator Image Build
  .github/workflows/pull-build-template-operator.yml
Labels: lgtm, area/ci, size/M, cla: yes

#248 chore: Rename pull-build-template-operator to build-template-operator
  .github/workflows/build-template-operator.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#249 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, lgtm, cla: yes

#247 chore: Remove module version file
  .github/workflows/create-release.yml
  .version
  scripts/release/validate_release_tag.sh
  scripts/release/validate_versions.sh
Labels: lgtm, area/ci, size/M, cla: yes

#250 chore: Drop validate pipeline
  .github/workflows/create-release.yml
  scripts/release/validate_pipeline_status.sh
Labels: lgtm, area/ci, size/S, cla: yes

#251 docs: Add mandatory sections to README.md
  README.md
Labels: lgtm, size/S, cla: yes

#252 chore: Make job support release by tag
  .github/workflows/build-template-operator.yml
Labels: lgtm, area/ci, size/S, cla: yes

#254 fix: Use workflow call to trigger image build during release
  .github/workflows/build-image.yml
  .github/workflows/create-release.yml
Labels: lgtm, area/ci, size/M, cla: yes

#255 fix: Add dependencies
  .github/workflows/create-release.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#256 chore: Check if release already exists
  .github/scripts/release/create_changelog.sh
  .github/scripts/release/draft_release.sh
  .github/scripts/release/get_release_by_tag.sh
  .github/scripts/release/publish_release.sh
  .github/scripts/release/upload_assets.sh
  .github/scripts/release/validate_release_tag.sh
  .github/scripts/release/wait_for_image.sh
  .github/workflows/build-image.yml
  .github/workflows/create-release.yml
Labels: lgtm, area/ci, size/M, cla: yes
