Repository kyma-project/template-operator, pull requests merged in 2024-10, with the labels that each got.

#262 chore: Allow dependabot monitor github actions
  .github/dependabot.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#266 chore: Bump golang version to 1.23.2
  Dockerfile
  go.mod
Labels: size/XS, cla: yes

#270 chore: Make build image accept multiple tags
  .github/workflows/build-image.yml
  .github/workflows/create-release.yml
Labels: lgtm, area/ci, size/S, cla: yes

#271 chore: Update lint-markdown-links version
  .github/workflows/lint-markdown-links.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#269 feat: Introduce modulereleasemeta to be used in E2E tests
  module-config.yaml
  module-release-meta.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S, cla: yes

#272 chore: Fix Build Image tags
  .github/workflows/build-image.yml
Labels: lgtm, area/ci, size/M, cla: yes

#278 deps: Bump k8s.io/apimachinery
  api/go.mod
  api/go.sum
  go.mod
Labels: size/XS, lgtm, cla: yes
