Repository kyma-project/template-operator, pull requests merged in 2024-02, with the labels that each got.

#148 feat: Add final-deletion-state Flag to Set Custom State When DeletionTimestamp is Set
  config/default/kustomization.yaml
  controllers/sample_controller_rendered_resources.go
  controllers/sample_controller_rendered_resources_test.go
  controllers/suite_test.go
  main.go
Labels: lgtm, size/L, cla: yes

#151 fix: Selecting Kyma CLI Binary Based on OS
  .version
  Makefile
  module-config.yaml
  scripts/local/get_kyma_file_name.sh
  sec-scanners-config.yaml
Labels: lgtm, size/S, cla: yes

#152 fix: Asset Uploading
  .version
  Makefile
  module-config.yaml
  scripts/local/get_kyma_file_name.sh
  sec-scanners-config.yaml
Labels: lgtm, size/S, cla: yes

#150 fix: Only add finalizer if the object is not under deletion
  controllers/sample_controller_rendered_resources.go
  controllers/sample_controller_rendered_resources_test.go
Labels: lgtm, size/M, cla: yes

#154 chore: Create GitHub actions for linting, tests and release assets
  .github/workflows/integration-test.yml
  .github/workflows/lint-golangci.yml
Labels: lgtm, area/ci, size/M, cla: yes

#160 chore: Bump docker builder base image to `golang:1.22-alpine`
  Dockerfile
Labels: size/XS, lgtm, cla: yes

#161 chore: Bump golangci-lint make and action
  .github/workflows/lint-golangci.yml
  Makefile
Labels: size/XS, lgtm, area/ci, cla: yes
