Repository kyma-project/template-operator, pull requests merged in 2024-11, with the labels that each got.

#283 fix: Build image event name
  .github/workflows/build-image.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#281 chore: Add linter config
  .github/workflows/lint-golangci.yml
  .golangci.yaml
  Makefile
  api/v1alpha1/sample_types.go
  controllers/sample_controller_rendered_resources.go
  controllers/sample_controller_rendered_resources_test.go
  controllers/suite_test.go
  main.go
Labels: lgtm, area/ci, size/L, cla: yes

#284 feat: Update ModuleConfig file with the required ModuleCatalog fields
  module-config.yaml
Labels: lgtm, size/S, cla: yes

#285 chore: Fix moduleconfig rawManifest in resources
  module-config.yaml
Labels: size/XS, lgtm, cla: yes

#295 feat: Migrate to checkmarxone
  sec-scanners-config.yaml
Labels: size/XS, cla: yes
