Repository kyma-project/template-operator, pull requests merged in 2025-03, with the labels that each got.

#332 chore: Limit GH workflow permissions
  .github/workflows/build-image.yml
  .github/workflows/create-release.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint-conventional-prs.yml
  .github/workflows/lint-golangci.yml
  .github/workflows/lint-markdown-links.yml
  .github/workflows/report-sprint-commits.yml
Labels: lgtm, area/ci, size/S, cla: yes

#333 chore: Update sec scanners config for checkmarxone migration
  sec-scanners-config.yaml
Labels: size/S, cla: yes

#334 chore: Add "contents: write" Permission to Create Release Workflow
  .github/workflows/create-release.yml
Labels: size/XS, lgtm, area/ci

#335 chore: Add "latest" Image Tag to BDBA Scan
  sec-scanners-config.yaml
Labels: size/XS, lgtm
